spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/clever
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-prod.xml
    enabled: true