spring:
  application:
    name: comment
  datasource:
    url: jdbc:postgresql://localhost:5432/clever
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
server:
  port: 8082
token:
  signing:
    key: secret
